=== TomasMessineo/xsd-and-xslt-examples/ejemplos-xsd/persona/persona.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="persona">
        <xs:complexType>
            <xs:all>
                <xs:element name="datos" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dni" type="xs:integer" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="telefono" type="xs:integer" minOccurs="0" maxOccurs="3"/>
                            <xs:element name="domicilio" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="nombre" type="xs:string" minOccurs="1" maxOccurs="1"/>
                            <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TomasMessineo/xsd-and-xslt-examples/ejemplos-xsd/persona/persona1.xml
<?xml version="1.0" encoding="UTF-8"?>
    <persona 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="persona.xsd"
    >
        
        <datos>
            <dni> 22222222 </dni>
            <telefono> 2281222222 </telefono>
            <telefono> 2281333333 </telefono>
            <telefono> 2281444444 </telefono>
            <domicilio> Calle 212 al lado de mi patio </domicilio>
            <nombre> Tom√°s </nombre>
            <apellido> Messineo </apellido>
        </datos>

    </persona>
