=== TomasMessineo/xsd-and-xslt-examples/ejemplos-xsd/equipos con atributos/equipo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="equipos-arg">
        <xs:complexType>
            <xs:sequence>
                
                <xs:element name="equipo" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType mixed="true"> <!-- Este elemento complejo lleva mixed ya que tiene texto dentro. -->
                                    <xs:attribute name="sigla" type="xs:string" default=""/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="valoracion"/>
                            <xs:element name="deporte" type="xs:string" maxOccurs="5"/>
                        </xs:sequence>
                        <xs:attribute name="pais" type="xs:string" fixed="Argentina"/> <!-- Defino al atributo de equipos-arg fuera del sequence de mas abajo, no el de mas arriba -->
                    </xs:complexType>
                </xs:element>

                <xs:element name="descripcion" type="xs:string"/>
                <xs:element name="division" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== TomasMessineo/xsd-and-xslt-examples/ejemplos-xsd/equipos con atributos/equipo.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos-arg
    xsi:noNamespaceSchemaLocation="equipo.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
    <equipo pais="Argentina">
        Gran equipo, el mas grande de Argentina.
        <nombre sigla="CABJ"> Boca Juniors </nombre>
        <valoracion> 8.5 </valoracion>
        <deporte> Fútbol </deporte>
        <deporte> Handball </deporte>
        <deporte> Futsal </deporte>0
    </equipo>
    <equipo pais="Argentina">
        Gran equipo, pero no es mejor que boca.
        <nombre sigla="CARP"> River Plate </nombre>
        <valoracion> 9.0 </valoracion>
        <deporte> Fútbol </deporte>
        <deporte> Handball </deporte>
        <deporte> Futsal </deporte>
    </equipo>
    <equipo pais="Argentina">
        Es un equipo horrible, puaj que asco.
        <nombre sigla="RAC"> Racing Club </nombre>
        <valoracion> 8.0 </valoracion>
        <deporte> Fútbol </deporte>
        <deporte> Handball </deporte>
        <deporte> Futsal </deporte>
    </equipo>
    <equipo pais="Argentina">
        No se ni como juega.
        <nombre sigla="IND"> Independiente </nombre>
        <valoracion> 8.2 </valoracion>
        <deporte> Fútbol </deporte>
        <deporte> Handball </deporte>
        <deporte> Futsal </deporte>
    </equipo>
    <equipo pais="Argentina">
        <nombre sigla="EDLP"> Estudiantes de La Plata </nombre>
        <valoracion> 8.0 </valoracion>
        <deporte> Fútbol </deporte>
        <deporte> Handball </deporte>
        <deporte> Futsal </deporte>
    </equipo>
    <equipo pais="Argentina">
        <nombre sigla="GELP"> Gimnasia de La Plata </nombre>
        <valoracion> 9.0 </valoracion>
        <deporte> Fútbol </deporte>
        <deporte> Handball </deporte>
        <deporte> Futsal </deporte>
    </equipo>


    <descripcion> Estos son algunos de los equipos de Argentina. </descripcion>
    <division> 1 </division>
</equipos-arg>
